export const s = {
  wrap: { fontFamily: "'Sora', sans-serif", color: '#c9d1d9', padding: '8px 0' },
  heading: { fontSize: '20px', fontWeight: 700, color: '#f9fafb', marginBottom: '20px' },
  emptyBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: 'rgba(99,102,241,0.06)',
    border: '1px solid rgba(99,102,241,0.2)',
    borderRadius: '12px',
    padding: '16px 20px',
  },
  tableWrap: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '16px',
    overflow: 'hidden',
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    padding: '12px 16px',
    textAlign: 'left',
    fontSize: '11px',
    fontWeight: 700,
    color: '#4b5563',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    background: '#0a0e18',
    borderBottom: '1px solid #1e2738',
  },
  tr: { borderBottom: '1px solid #1e2738' },
  td: { padding: '14px 16px', fontSize: '13px', color: '#9ca3af', verticalAlign: 'middle' },
  codeBtn: {
    background: 'rgba(99,102,241,0.1)',
    border: '1px solid rgba(99,102,241,0.25)',
    borderRadius: '8px',
    color: '#a5b4fc',
    fontSize: '12px',
    fontWeight: 600,
    padding: '6px 14px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },
  // Modal
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.7)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalBox: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '16px',
    padding: '28px',
    width: '100%',
    maxWidth: '860px',
    maxHeight: '85vh',
    overflowY: 'auto',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '16px',
  },
  modalTitle: { fontSize: '18px', fontWeight: 700, color: '#f9fafb', margin: 0 },
  closeBtn: {
    background: 'transparent',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#6b7280',
    padding: '6px 8px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
  },
  badgeOutline: {
    borderRadius: '999px',
    fontSize: '11px',
    fontWeight: 600,
    padding: '3px 10px',
    background: 'transparent',
    border: '1px solid #1e2738',
    color: '#6b7280',
  },
  codeBlock: {
    background: '#080c14',
    border: '1px solid #1e2738',
    borderRadius: '12px',
    padding: '20px',
    color: '#c9d1d9',
    fontSize: '13px',
    fontFamily: 'monospace',
    overflowX: 'auto',
    lineHeight: 1.6,
    margin: 0,
  },
  closeActionBtn: {
    background: '#0a0e18',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#9ca3af',
    fontSize: '13px',
    fontWeight: 600,
    padding: '8px 20px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },
};
