export const s = {
  page: {
    minHeight: '100vh',
    background: '#080c14',
    color: '#c9d1d9',
    fontFamily: "'Sora', sans-serif",
  },
  navbar: {
    height: '64px',
    background: '#080c14',
    borderBottom: '1px solid #1e2738',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 40px',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  logo: { fontSize: '22px', fontWeight: 700, color: '#a5b4fc', letterSpacing: '0.01em' },

  // ── User button in navbar — slightly different from filter buttons ─────
  userBtn: {
    background: 'transparent',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#9ca3af',
    fontSize: '14px',
    fontWeight: 600,
    padding: '8px 14px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },

  dropdown: {
    position: 'absolute',
    right: 0,
    top: 'calc(100% + 8px)',
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '12px',
    overflow: 'hidden',
    minWidth: '200px',
    zIndex: 200,
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
  },
  dropdownItem: {
    display: 'block',
    width: '100%',
    padding: '12px 18px',
    fontSize: '14px',
    color: '#9ca3af',
    textDecoration: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },

  main: { padding: '32px 40px' },
  searchWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    marginBottom: '20px',
  },
  searchIcon: {
    position: 'absolute',
    left: '16px',
    width: '16px',
    height: '16px',
    color: '#4b5563',
    pointerEvents: 'none',
    flexShrink: 0,
  },
  searchInput: {
    width: '100%',
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '12px',
    color: '#e2e8f0',
    fontSize: '14px',
    fontWeight: 500,
    padding: '12px 44px',
    outline: 'none',
    fontFamily: "'Sora', sans-serif",
    boxSizing: 'border-box',
    transition: 'border-color 0.2s',
  },
  searchClear: {
    position: 'absolute',
    right: '16px',
    background: 'transparent',
    border: 'none',
    color: '#4b5563',
    cursor: 'pointer',
    fontSize: '14px',
    padding: '4px',
    lineHeight: 1,
  },

  filterRow: {
    display: 'flex',
    gap: '12px',
    marginBottom: '16px',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },

  // ── Unified filter button — used by ALL three dropdowns ───────────────
  selectWrapper: { position: 'relative' },
  selectBtn: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    color: '#9ca3af',
    fontSize: '14px',
    fontWeight: 500,
    // fixed padding — same on every OS, no OS chrome to fight
    padding: '10px 14px 10px 16px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    minWidth: '160px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
    outline: 'none',
    userSelect: 'none',
  },

  // ── Dropdown list for single-select ──────────────────────────────────
  selectDropdown: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    minWidth: '100%',
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    overflow: 'hidden',
    zIndex: 150,
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
  },
  selectOption: {
    display: 'block',
    width: '100%',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 500,
    color: '#9ca3af',
    background: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    whiteSpace: 'nowrap',
  },
  selectOptionActive: {
    color: '#a5b4fc',
    background: 'rgba(99,102,241,0.1)',
  },

  tagDropdownWrapper: { position: 'relative' },
  tagDropdownPanel: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '14px',
    padding: '16px',
    zIndex: 150,
    width: '360px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
  },
  tagGrid: { display: 'flex', flexWrap: 'wrap', gap: '8px' },
  tagPill: {
    background: 'rgba(99,102,241,0.08)',
    border: '1px solid rgba(99,102,241,0.15)',
    borderRadius: '999px',
    color: '#6b7280',
    fontSize: '12px',
    fontWeight: 600,
    padding: '5px 12px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    transition: 'all 0.15s',
  },
  tagPillActive: {
    background: 'rgba(99,102,241,0.25)',
    border: '1px solid rgba(99,102,241,0.5)',
    color: '#a5b4fc',
  },
  clearTagsBtn: {
    marginTop: '12px',
    background: 'transparent',
    border: 'none',
    color: '#6366f1',
    fontSize: '13px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    padding: 0,
  },
  clearAllBtn: {
    background: 'transparent',
    border: '1px solid rgba(239,68,68,0.3)',
    borderRadius: '10px',
    color: '#ef4444',
    fontSize: '13px',
    fontWeight: 600,
    padding: '10px 16px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    alignSelf: 'flex-start',
  },
  activeTagPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(99,102,241,0.15)',
    border: '1px solid rgba(99,102,241,0.3)',
    borderRadius: '999px',
    color: '#a5b4fc',
    fontSize: '12px',
    fontWeight: 600,
    padding: '4px 10px 4px 12px',
  },
  removeTagBtn: {
    background: 'transparent',
    border: 'none',
    color: '#6366f1',
    cursor: 'pointer',
    fontSize: '11px',
    padding: 0,
    lineHeight: 1,
    fontFamily: "'Sora', sans-serif",
  },
  problemList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  problemCard: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '16px',
    padding: '22px 28px',
  },
  problemCardTop: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  problemNo: { fontSize: '13px', fontWeight: 600, color: '#4b5563', minWidth: '32px' },
  problemTitle: { fontSize: '17px', fontWeight: 600, color: '#e2e8f0', textDecoration: 'none' },
  solvedBadge: {
    background: 'rgba(34,197,94,0.1)',
    border: '1px solid rgba(34,197,94,0.25)',
    borderRadius: '999px',
    color: '#22c55e',
    fontSize: '12px',
    fontWeight: 700,
    padding: '4px 14px',
    flexShrink: 0,
  },
  badgeRow: { display: 'flex', gap: '8px', flexWrap: 'wrap' },
  tagBadge: {
    background: 'rgba(99,102,241,0.1)',
    border: '1px solid rgba(99,102,241,0.2)',
    borderRadius: '999px',
    color: '#a5b4fc',
    fontSize: '12px',
    fontWeight: 600,
    padding: '4px 12px',
  },
  emptyState: { textAlign: 'center', color: '#4b5563', fontSize: '15px', padding: '60px 0' },
  inlineClear: {
    background: 'transparent',
    border: 'none',
    color: '#6366f1',
    cursor: 'pointer',
    fontSize: '15px',
    textDecoration: 'underline',
    fontFamily: "'Sora', sans-serif",
  },
  paginationInfo: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#4b5563',
    marginTop: '32px',
    marginBottom: '20px',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '8px',
    paddingBottom: '40px',
    flexWrap: 'wrap',
  },
  pageBtn: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#9ca3af',
    fontSize: '14px',
    fontWeight: 600,
    padding: '8px 18px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },
  pageBtnActive: { background: '#4f46e5', border: '1px solid #6366f1', color: '#fff' },
};
