export const s = {
  page: {
    minHeight: "100vh",
    background: "#080c14",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px",
    fontFamily: "'Sora', sans-serif",
  },
  card: {
    width: "100%",
    maxWidth: "420px",
    background: "#0c1018",
    border: "1px solid #1e2738",
    borderRadius: "20px",
    padding: "44px 40px",
    boxShadow: "0 24px 64px rgba(0,0,0,0.5)",
  },
  logoArea: {
    textAlign: "center",
    marginBottom: "36px",
  },
  logo: {
    fontSize: "32px",
    fontWeight: 700,
    color: "#a5b4fc",
    marginBottom: "6px",
  },
  tagline: {
    fontSize: "13px",
    color: "#4b5563",
    fontWeight: 500,
  },
  errorBanner: {
    background: "rgba(239,68,68,0.08)",
    border: "1px solid rgba(239,68,68,0.2)",
    borderRadius: "10px",
    color: "#f87171",
    fontSize: "13px",
    padding: "10px 14px",
    marginBottom: "20px",
    textAlign: "center",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  fieldGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    fontSize: "13px",
    fontWeight: 600,
    color: "#9ca3af",
  },
  input: {
    width: "100%",
    background: "#080c14",
    border: "1px solid #1e2738",
    borderRadius: "10px",
    color: "#e2e8f0",
    fontSize: "14px",
    padding: "11px 14px",
    outline: "none",
    boxSizing: "border-box",
    fontFamily: "'Sora', sans-serif",
  },
  inputError: {
    borderColor: "rgba(239,68,68,0.5)",
  },
  errorMsg: {
    fontSize: "12px",
    color: "#f87171",
  },
  passwordWrapper: {
    position: "relative",
  },
  passwordTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  forgotLink: {
    color: "#a5b4fc",
    fontSize: "12px",
    textDecoration: "none",
    fontWeight: 500,
  },
  eyeBtn: {
    position: "absolute",
    top: "50%",
    right: "12px",
    transform: "translateY(-50%)",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "#4b5563",
    display: "flex",
    alignItems: "center",
    padding: 0,
  },
  submitBtn: {
    background: "#4f46e5",
    border: "1px solid #6366f1",
    borderRadius: "10px",
    color: "#fff",
    fontSize: "14px",
    fontWeight: 700,
    padding: "12px",
    cursor: "pointer",
    marginTop: "8px",
    fontFamily: "'Sora', sans-serif",
  },
  footer: {
    textAlign: "center",
    marginTop: "28px",
    fontSize: "13px",
    color: "#4b5563",
  },
  link: {
    color: "#a5b4fc",
    fontWeight: 600,
    textDecoration: "none",
  },
};