export const s = {
  page: {
    minHeight: '100vh',
    background: '#080c14',
    fontFamily: "'Sora', sans-serif",
    color: '#c9d1d9',
  },
  navbar: {
    height: '64px',
    background: '#080c14',
    borderBottom: '1px solid #1e2738',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 40px',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navLeft: { display: 'flex', alignItems: 'center', gap: '20px' },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'transparent',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#9ca3af',
    fontSize: '13px',
    fontWeight: 600,
    padding: '6px 14px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },
  logo: { fontSize: '20px', fontWeight: 700, color: '#a5b4fc' },
  adminLink: { textDecoration: 'none' },
  adminBox: {
    fontSize: '13px',
    color: '#6b7280',
    fontWeight: 500,
    border: '1px solid #1e2738',
    borderRadius: '8px',
    padding: '6px 14px',
    background: '#0c1018',
  },
  main: { padding: '48px 40px', maxWidth: '950px', margin: '0 auto' },
  header: { marginBottom: '36px' },
  heading: { fontSize: '28px', fontWeight: 700, color: '#f9fafb' },
  subheading: { fontSize: '14px', color: '#6b7280', marginTop: '8px' },
  card: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '16px',
    padding: '28px',
    marginBottom: '28px',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: 700,
    marginBottom: '20px',
    paddingBottom: '12px',
    borderBottom: '1px solid #1e2738',
  },
  formGroup: { marginBottom: '18px' },
  label: {
    display: 'block',
    fontSize: '11px',
    fontWeight: 700,
    color: '#4b5563',
    textTransform: 'uppercase',
    marginBottom: '8px',
  },
  input: {
    width: '100%',
    background: '#080c14',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    color: '#e2e8f0',
    padding: '12px 14px',
    outline: 'none',
    boxSizing: 'border-box',
  },
  textarea: {
    width: '100%',
    background: '#080c14',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    color: '#e2e8f0',
    padding: '12px 14px',
    outline: 'none',
    resize: 'vertical',
    boxSizing: 'border-box',
    lineHeight: 1.6,
  },
  select: {
    width: '100%',
    background: '#080c14',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    color: '#e2e8f0',
    padding: '12px 14px',
    outline: 'none',
  },
  inputError: { borderColor: '#ef4444' },
  errorText: { fontSize: '12px', color: '#f87171', marginTop: '6px' },
  row: { display: 'flex', gap: '20px', flexWrap: 'wrap' },
  tagWrap: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginTop: '10px' },
  tagPill: {
    background: 'rgba(99,102,241,0.1)',
    border: '1px solid rgba(99,102,241,0.2)',
    borderRadius: '999px',
    color: '#a5b4fc',
    fontSize: '11px',
    padding: '4px 10px',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  sectionTitle: { fontSize: '14px', fontWeight: 600 },
  addBtn: {
    background: 'rgba(99,102,241,0.1)',
    border: '1px solid rgba(99,102,241,0.2)',
    borderRadius: '8px',
    color: '#a5b4fc',
    padding: '7px 14px',
    cursor: 'pointer',
  },
  removeBtn: {
    background: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.2)',
    borderRadius: '6px',
    color: '#f87171',
    padding: '4px 10px',
    cursor: 'pointer',
  },
  caseCard: {
    background: '#080c14',
    border: '1px solid #1e2738',
    borderRadius: '12px',
    padding: '16px',
  },
  caseTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  caseLabel: { fontSize: '12px', fontWeight: 700, color: '#6b7280' },
  column: { display: 'flex', flexDirection: 'column', gap: '14px' },
  codeArea: {
    width: '100%',
    background: '#080c14',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    color: '#e2e8f0',
    padding: '12px 14px',
    marginBottom: '10px',
    resize: 'vertical',
    fontFamily: 'monospace',
    boxSizing: 'border-box',
  },
  langBadge: {
    background: 'rgba(234,179,8,0.1)',
    border: '1px solid rgba(234,179,8,0.25)',
    borderRadius: '8px',
    color: '#eab308',
    padding: '5px 12px',
    fontSize: '12px',
    fontWeight: 600,
  },
  codeWrap: { display: 'flex', flexDirection: 'column', gap: '28px' },
  rateLimitBanner: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.2)',
    borderRadius: '12px',
    padding: '14px 18px',
    marginBottom: '16px',
  },
  submitBtn: {
    width: '100%',
    background: 'rgba(99,102,241,0.15)',
    border: '1px solid rgba(99,102,241,0.35)',
    borderRadius: '12px',
    color: '#a5b4fc',
    fontSize: '15px',
    fontWeight: 700,
    padding: '15px',
    cursor: 'pointer',
  },
};
