export const s = {
  page: {
    minHeight: '100vh',
    background: '#080c14',
    fontFamily: "'Sora', sans-serif",
    color: '#c9d1d9',
  },
  navbar: {
    height: '64px',
    background: '#080c14',
    borderBottom: '1px solid #1e2738',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 40px',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navLeft: { display: 'flex', alignItems: 'center', gap: '20px' },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'transparent',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#9ca3af',
    fontSize: '13px',
    fontWeight: 600,
    padding: '6px 14px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },
  logo: { fontSize: '20px', fontWeight: 700, color: '#a5b4fc' },
  adminBox: {
    fontSize: '13px',
    color: '#6b7280',
    fontWeight: 500,
    border: '1px solid #1e2738',
    borderRadius: '8px',
    padding: '6px 14px',
    background: '#0c1018',
  },
  main: { padding: '48px 40px', maxWidth: '1200px', margin: '0 auto' },
  header: { marginBottom: '36px' },
  heading: { fontSize: '28px', fontWeight: 700, color: '#f9fafb', marginBottom: '8px' },
  subheading: { fontSize: '14px', color: '#6b7280' },

  searchWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    marginBottom: '20px',
  },
  searchIcon: {
    position: 'absolute',
    left: '16px',
    width: '16px',
    height: '16px',
    color: '#4b5563',
    pointerEvents: 'none',
  },
  searchInput: {
    width: '100%',
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '12px',
    color: '#e2e8f0',
    fontSize: '14px',
    fontWeight: 500,
    padding: '12px 44px',
    outline: 'none',
    fontFamily: "'Sora', sans-serif",
    boxSizing: 'border-box',
  },
  searchClear: {
    position: 'absolute',
    right: '16px',
    background: 'transparent',
    border: 'none',
    color: '#4b5563',
    cursor: 'pointer',
    fontSize: '14px',
  },

  filterRow: {
    display: 'flex',
    gap: '12px',
    marginBottom: '16px',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },

  selectWrapper: { position: 'relative' },
  selectBtn: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    color: '#9ca3af',
    fontSize: '14px',
    fontWeight: 500,
    padding: '10px 14px 10px 16px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    minWidth: '160px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '10px',
    outline: 'none',
    userSelect: 'none',
  },
  selectDropdown: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    minWidth: '100%',
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '10px',
    overflow: 'hidden',
    zIndex: 150,
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
  },
  selectOption: {
    display: 'block',
    width: '100%',
    padding: '10px 16px',
    fontSize: '14px',
    fontWeight: 500,
    color: '#9ca3af',
    background: 'transparent',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    whiteSpace: 'nowrap',
  },
  selectOptionActive: { color: '#a5b4fc', background: 'rgba(99,102,241,0.1)' },

  tagDropdownWrapper: { position: 'relative' },
  tagDropdownPanel: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '14px',
    padding: '16px',
    zIndex: 150,
    width: '360px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
  },
  tagGrid: { display: 'flex', flexWrap: 'wrap', gap: '8px' },
  tagPill: {
    background: 'rgba(99,102,241,0.08)',
    border: '1px solid rgba(99,102,241,0.15)',
    borderRadius: '999px',
    color: '#6b7280',
    fontSize: '12px',
    fontWeight: 600,
    padding: '5px 12px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },
  tagPillActive: {
    background: 'rgba(99,102,241,0.25)',
    border: '1px solid rgba(99,102,241,0.5)',
    color: '#a5b4fc',
  },
  clearTagsBtn: {
    marginTop: '12px',
    background: 'transparent',
    border: 'none',
    color: '#6366f1',
    fontSize: '13px',
    cursor: 'pointer',
  },
  clearAllBtn: {
    background: 'transparent',
    border: '1px solid rgba(239,68,68,0.3)',
    borderRadius: '10px',
    color: '#ef4444',
    fontSize: '13px',
    fontWeight: 600,
    padding: '10px 16px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    alignSelf: 'flex-start',
  },

  activeTagsRow: { display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '20px' },
  activeTagPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    background: 'rgba(99,102,241,0.15)',
    border: '1px solid rgba(99,102,241,0.3)',
    borderRadius: '999px',
    color: '#a5b4fc',
    fontSize: '12px',
    fontWeight: 600,
    padding: '4px 10px 4px 12px',
  },
  removeTagBtn: {
    background: 'transparent',
    border: 'none',
    color: '#6366f1',
    cursor: 'pointer',
    fontSize: '11px',
  },

  tableWrap: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '16px',
    overflow: 'hidden',
  },
  table: { width: '100%', borderCollapse: 'collapse' },
  th: {
    padding: '14px 20px',
    textAlign: 'left',
    fontSize: '12px',
    fontWeight: 700,
    color: '#4b5563',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    background: '#0a0e18',
    borderBottom: '1px solid #1e2738',
  },
  tr: { borderBottom: '1px solid #1e2738' },
  td: { padding: '16px 20px', fontSize: '14px', color: '#9ca3af', verticalAlign: 'middle' },
  tagRow: { display: 'flex', flexWrap: 'wrap', gap: '6px' },
  tag: {
    background: 'rgba(99,102,241,0.1)',
    border: '1px solid rgba(99,102,241,0.2)',
    borderRadius: '999px',
    color: '#a5b4fc',
    fontSize: '11px',
    fontWeight: 600,
    padding: '3px 9px',
  },
  updateBtn: {
    background: 'rgba(234,179,8,0.1)',
    border: '1px solid rgba(234,179,8,0.25)',
    borderRadius: '8px',
    color: '#eab308',
    fontSize: '13px',
    fontWeight: 600,
    padding: '7px 16px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },

  paginationInfo: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#4b5563',
    marginTop: '32px',
    marginBottom: '20px',
  },
  pagination: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '8px',
    paddingBottom: '40px',
    flexWrap: 'wrap',
  },
  pageBtn: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#9ca3af',
    fontSize: '13px',
    fontWeight: 600,
    padding: '8px 14px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
    minWidth: '40px',
  },
  pageBtnActive: { background: '#4f46e5', border: '1px solid #6366f1', color: '#fff' },
};
