export const s = {
  page: {
    minHeight: '100vh',
    background: '#080c14',
    fontFamily: "'Sora', sans-serif",
    color: '#c9d1d9',
  },
  navbar: {
    height: '64px',
    background: '#080c14',
    borderBottom: '1px solid #1e2738',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 40px',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navLeft: { display: 'flex', alignItems: 'center', gap: '20px' },
  backBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    background: 'transparent',
    border: '1px solid #1e2738',
    borderRadius: '8px',
    color: '#9ca3af',
    fontSize: '13px',
    fontWeight: 600,
    padding: '6px 14px',
    cursor: 'pointer',
    fontFamily: "'Sora', sans-serif",
  },
  logo: { fontSize: '20px', fontWeight: 700, color: '#a5b4fc' },
  adminLink: { textDecoration: 'none' },
  adminBox: {
    fontSize: '13px',
    color: '#6b7280',
    fontWeight: 500,
    border: '1px solid #1e2738',
    borderRadius: '8px',
    padding: '6px 14px',
    background: '#0c1018',
  },
  main: { padding: '48px 40px', maxWidth: '600px', margin: '0 auto' },
  header: { marginBottom: '32px' },
  heading: { fontSize: '28px', fontWeight: 700, color: '#f9fafb', marginBottom: '8px' },
  subheading: { fontSize: '14px', color: '#6b7280' },
  card: {
    background: '#0c1018',
    border: '1px solid #1e2738',
    borderRadius: '16px',
    padding: '32px',
  },
  formGroup: { marginBottom: '20px' },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 600,
    color: '#9ca3af',
    marginBottom: '10px',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  fileLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    border: '1px dashed #1e2738',
    borderRadius: '12px',
    padding: '20px',
    cursor: 'pointer',
    background: '#0a0e18',
    transition: 'border-color 0.2s',
  },
  fileLabelError: { borderColor: 'rgba(239,68,68,0.4)' },
  errorText: { fontSize: '12px', color: '#f87171', marginTop: '6px' },
  infoBox: {
    background: 'rgba(99,102,241,0.06)',
    border: '1px solid rgba(99,102,241,0.2)',
    borderRadius: '10px',
    padding: '14px 16px',
    marginBottom: '20px',
  },
  progressWrap: { marginBottom: '20px' },
  progressBg: { background: '#1e2738', borderRadius: '999px', height: '6px', overflow: 'hidden' },
  progressFill: {
    background: 'linear-gradient(90deg, #6366f1, #a5b4fc)',
    height: '100%',
    borderRadius: '999px',
    transition: 'width 0.3s ease',
  },
  errorBox: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    background: 'rgba(239,68,68,0.08)',
    border: '1px solid rgba(239,68,68,0.2)',
    borderRadius: '10px',
    padding: '14px 16px',
    marginBottom: '20px',
  },
  successBox: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    background: 'rgba(34,197,94,0.08)',
    border: '1px solid rgba(34,197,94,0.2)',
    borderRadius: '10px',
    padding: '14px 16px',
    marginBottom: '20px',
  },
  submitBtn: {
    background: 'rgba(99,102,241,0.15)',
    border: '1px solid rgba(99,102,241,0.35)',
    borderRadius: '8px',
    color: '#a5b4fc',
    fontSize: '13px',
    fontWeight: 600,
    padding: '9px 24px',
    fontFamily: "'Sora', sans-serif",
  },
};
