const LANGUAGE_IDS = {
  cpp: 54,
  java: 62,
  javascript: 63,
};

const MAX_POLLING_RETRIES = 10;

const POLLING_INTERVAL = 1000;

const MAX_BATCH_SIZE = 15;

const MAX_REFERENCE_VALIDATION_TESTCASES = 10;

const CPU_TIME_MULTIPLIER = 3;

const WALL_TIME_MULTIPLIER = 5;

module.exports = {
  LANGUAGE_IDS,
  MAX_POLLING_RETRIES,
  POLLING_INTERVAL,
  MAX_BATCH_SIZE,
  MAX_REFERENCE_VALIDATION_TESTCASES,
  CPU_TIME_MULTIPLIER,
  WALL_TIME_MULTIPLIER,
};
