const LOGIN_LIMIT = 10;
const LOGIN_DURATION = 15 * 60;

const CHANGE_PASSWORD_LIMIT = 5;
const CHANGE_PASSWORD_DURATION = 15 * 60;

const REGISTER_LIMIT = 5;
const REGISTER_DURATION = 60 * 60;

const RUN_LIMIT = 3;
const RUN_REFILL_RATE_PER_SEC = 4 / 60;

const SUBMIT_LIMIT = 3;
const SUBMIT_REFILL_RATE_PER_SEC = 2 / 60;

module.exports = {
  LOGIN_LIMIT,
  LOGIN_DURATION,
  CHANGE_PASSWORD_LIMIT,
  CHANGE_PASSWORD_DURATION,
  REGISTER_LIMIT,
  REGISTER_DURATION,
  RUN_LIMIT,
  RUN_REFILL_RATE_PER_SEC,
  SUBMIT_LIMIT,
  SUBMIT_REFILL_RATE_PER_SEC,
};
